name: Node-Check-Updates
on:
  repository_dispatch:
    types: [ncu]

jobs:
  ncu:
    name: Run NCU
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Update packages with NCU
        id: ncu-steps
        run: 
          npx npm-check-updates -u
          && git config --global user.email "wolfemikl@gmail.com"
          && git config --global user.name "Mikl Wolfe"
          && git commit -am 'Update dependencies'
          && git push origin main
