export const baseRules = {
  'boundaries/element-types': [
    'warn',
    {
      default: 'disallow',
      rules: [
        { allow: ['utils'], from: 'utils' },
        { allow: ['features', 'shared', 'utils'], from: 'features' },
        { allow: ['shared', 'utils'], from: 'shared' },
      ],
    },
  ],
  camelcase: [
    'error',
    {
      ignoreDestructuring: true,
      ignoreGlobals: true,
      ignoreImports: true,
      properties: 'never',
    },
  ],
  'class-methods-use-this': 'off',
  complexity: ['error', { max: 15 }],
  'constructor-super': 'warn',
  'dot-notation': 'warn',
  'filenames/match-regex': 'off',
  'func-names': 'off',
  'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
  'import/default': 'off',
  'import/extensions': ['warn', 'ignorePackages', { ts: 'never' }],
  'import/named': 'off',
  'import/namespace': 'off',
  'import/no-commonjs': 'off',
  'import/no-cycle': [
    'error',
    {
      ignoreExternal: true,
      maxDepth: 1,
    },
  ],
  'import/no-duplicates': ['error', { 'prefer-inline': true }],
  'import/no-empty-named-blocks': 'error',
  'import/no-extraneous-dependencies': [
    'error',
    {
      devDependencies: ['**/*.test.{js,ts}', '**/*.spec.{js,ts}', '**/test/**'],
    },
  ],
  'import/no-import-module-exports': 'error',
  'import/no-named-as-default-member': 'off',
  'import/no-namespace': 'error',
  'import/no-relative-packages': 'error',
  'import/no-relative-parent-imports': [
    'error',
    {
      ignore: ['@/components', '@/utils', '@/types'],
    },
  ],
  'import/no-self-import': 'error',
  'import/no-unresolved': [
    'error',
    { amd: true, commonjs: true, ignore: ['^node:'] },
  ],
  'import/order': [
    'warn',
    {
      alphabetize: {
        order: 'asc',
      },
      'newlines-between': 'always',
    },
  ],
  'jsx-quotes': 'warn',
  'keyword-spacing': 'warn',
  'logical-assignment-operators': [
    'warn',
    'always',
    { enforceForIfStatements: true },
  ],
  'max-classes-per-file': ['error', 1],
  'n/no-unsupported-features/es-syntax': [
    'error',
    {
      ignores: ['modules', 'dynamicImport'],
      version: '>=18.0.0',
    },
  ],
  'no-array-constructor': 'error',
  'no-await-in-loop': 'warn',
  'no-caller': 'warn',
  'no-confusing-arrow': 'warn',
  'no-console': 'off',
  'no-const-assign': 'warn',
  'no-constant-binary-expression': 'error',
  'no-constant-condition': 'error',
  'no-delete-var': 'warn',
  'no-dupe-class-members': 'warn',
  'no-dupe-keys': 'warn',
  'no-duplicate-imports': 'error',
  'no-else-return': 'warn',
  'no-empty': 'off',
  'no-empty-pattern': 'off',
  'no-extra-bind': 'warn',
  'no-extra-parens': 'off',
  'no-extra-semi': 'warn',
  'no-floating-decimal': 'warn',
  'no-implicit-coercion': [
    'error',
    { boolean: false, number: true, string: true },
  ],
  'no-iterator': 'warn',
  'no-lonely-if': 'warn',
  'no-mixed-spaces-and-tabs': ['warn', 'smart-tabs'],
  'no-multi-str': 'warn',
  'no-new-object': 'error',
  'no-new-wrappers': 'warn',
  'no-process-exit': 'off',
  'no-promise-executor-return': ['error', { allowVoid: true }],
  'no-proto': 'warn',
  'no-redeclare': 'warn',
  'no-restricted-syntax': [
    'warn',
    {
      message:
        'for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.',
      selector: 'ForInStatement',
    },
    {
      message:
        'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.',
      selector: 'LabeledStatement',
    },
    {
      message:
        '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.',
      selector: 'WithStatement',
    },
    {
      message: 'Provide initialValue to reduce',
      selector:
        "CallExpression[callee.property.name='reduce'][arguments.length<2]",
    },
    {
      message: 'Use for...of instead',
      selector: "CallExpression[callee.property.name='forEach']",
    },
  ],
  'no-shadow': 'off',
  'no-shadow-restricted-names': 'warn',
  'no-spaced-func': 'warn',
  'no-this-before-super': 'warn',
  'no-undef-init': 'warn',
  'no-underscore-dangle': 'off',
  'no-unneeded-ternary': 'warn',
  'no-unreachable': 'error',
  'no-unsafe-optional-chaining': 'error',
  'no-unused-private-class-members': 'warn',
  'no-unused-vars': [
    'warn',
    {
      args: 'after-used',
      ignoreRestSiblings: true,
    },
  ],
  'no-useless-call': 'warn',
  'no-useless-computed-key': 'warn',
  'no-useless-concat': 'warn',
  'no-useless-constructor': 'warn',
  'no-useless-escape': 'warn',
  'no-useless-rename': 'warn',
  'no-useless-return': 'warn',
  'no-var': 'warn',
  'no-with': 'warn',
  'object-curly-spacing': ['off', 'always'],
  'object-shorthand': 'warn',
  'optimize-regex/optimize-regex': 'warn',
  'perfectionist/sort-named-imports': [
    'error',
    {
      'ignore-case': true,
      order: 'asc',
      type: 'natural',
    },
  ],
  'perfectionist/sort-objects': [
    'error',
    {
      order: 'asc',
      'spread-last': true,
      type: 'natural',
    },
  ],
  'prefer-arrow-callback': 'warn',
  'prefer-const': 'warn',
  'prefer-destructuring': [
    'warn',
    {
      array: false,
      object: true,
    },
  ],
  'prefer-exponentiation-operator': 'error',
  'prefer-object-has-own': 'error',
  'prefer-rest-params': 'warn',
  'prefer-spread': 'warn',
  'prefer-template': 'warn',
  'prettier/prettier': ['warn', { parser: 'babel' }],
  'promise/no-multiple-resolved': 'error',
  'promise/no-nesting': 'warn',
  'promise/prefer-await-to-callbacks': 'warn',
  'promise/prefer-await-to-then': 'warn',
  'quote-props': ['warn', 'as-needed'],
  quotes: [
    'off',
    'single',
    {
      allowTemplateLiterals: true,
      avoidEscape: true,
    },
  ],
  radix: 'warn',
  'regexp/no-missing-g-flag': 'error',
  'require-atomic-updates': ['error', { allowProperties: false }],
  'rest-spread-spacing': 'off',
  'security/detect-buffer-noassert': 'error',
  'security/detect-child-process': 'warn',
  'security/detect-disable-mustache-escape': 'error',
  'security/detect-non-literal-fs-filename': 'error',
  'security/detect-non-literal-regexp': 'error',
  'security/detect-non-literal-require': 'error',
  'security/detect-possible-timing-attacks': 'error',
  'security/detect-unsafe-regex': 'error',
  semi: 'off',
  'sort-destructure-keys/sort-destructure-keys': 'warn',
  'sort-imports': 'off',
  'sort-vars': 'warn',
  'space-before-function-paren': [
    'off',
    { anonymous: 'always', asyncArrow: 'always', named: 'never' },
  ],
  'space-in-parens': ['off', 'never'],
  'spaced-comment': [
    'warn',
    'always',
    {
      block: {
        balanced: true,
        exceptions: ['*'],
        markers: ['!'],
      },
      line: {
        exceptions: ['-', '+'],
        markers: ['/'],
      },
    },
  ],
  strict: ['warn', 'never'],
  'unicode-bom': 'warn',
  'unicorn/catch-error-name': ['error', { name: 'error' }],
  'unicorn/filename-case': [
    'warn',
    {
      cases: {
        camelCase: true,
        pascalCase: true,
      },
      ignore: ['.*.md'],
    },
  ],
  'unicorn/import-index': 'warn',
  'unicorn/no-useless-undefined': ['error', { checkArguments: true }],
  'unicorn/prefer-array-flat': ['error', { functions: ['flatten'] }],
  'unicorn/prefer-at': 'error',
  'unicorn/prefer-blob-reading-methods': 'error',
  'unicorn/prefer-string-replace-all': 'error',
  'unicorn/prefer-string-slice': 'error',
  'unicorn/prefer-type-error': 'error',
  'unicorn/prevent-abbreviations': [
    'warn',
    {
      allowList: {
        e2e: true,
        params: true,
        props: true,
        ref: true,
      },
      ignore: [/e2e/],
    },
  ],
  'unicorn/require-post-message-target-origin': 'error',
  'write-good-comments/write-good-comments': 'warn',
};
