name: Bump version
on:
  push:
    branches:
      - main
jobs:
  bump:
    name: Bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
#       - run: 
#           tmp=$(mktemp)
#           && jq --arg version ${VERSION:1} '.version = $version' package.json > '$tmp'
#           && mv '$tmp' package.json
#           && cat ./package.json
#           && git config --global user.email "wolfemikl@gmail.com"
#           && git config --global user.name "Mikl Wolfe"
#           && git commit -am ${VERSION:1}
#           && git push origin main
#         env:
#           VERSION: ${{ steps.bump.outputs.tag }}
#           VERSION_JSON: ${{ toJSON(steps.bump.outputs.tag) }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - uses: actions/checkout@v3
      - name: Release new tag
        id: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
      - run: echo $TEST
        env:
          TEST: ${{ needs.bump }}
