name: Bump-N-Pub

on:
  push:
    branches:
      - main

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.bump-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump Tag
        id: bump-tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: tag
    permissions:
      contents: write
    env:
      VERSION: ${{ needs.tag.outputs.tag }}
    outputs:
      VERSION: ${{ env.VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Release Bumped Tag
        id: release-tag
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          
  package-bump:
      name: Package Bump
      runs-on: ubuntu-latest
      needs: publish-release
      env: 
        VERSION: ${{ needs.publish-release.outputs.VERSION }}
      outputs:
        SHA: ${{ steps.bump.outputs.SHA }}
      steps:
        - uses: actions/checkout@v3
        - name: Bump Package Version
          id: bump
          run: 
            tmp=$(mktemp)
            && jq --arg version ${VERSION} '.version = $version' package.json > '$tmp'
            && mv '$tmp' package.json
            && git config --global user.email "wolfemikl@gmail.com"
            && git config --global user.name "Mikl Wolfe"
            && git commit -am ${VERSION}
            && git push origin main
            && echo ::set-output name=SHA::$(git rev-parse origin/main)
          
  publish-github:
      name: Publish Github
      runs-on: ubuntu-latest
      needs: package-bump
      permissions:
        contents: read
        packages: write
      env:
        SHA: ${{ needs.package-bump.outputs.SHA }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ref: ${{ env.SHA }}
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            registry-url: 'https://npm.pkg.github.com'
            scope: '@mikey-pro'
        - name: Publish to Github
          id: github-steps
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
      name: Publish Npm
      runs-on: ubuntu-latest
      needs: package-bump
      env:
        SHA: ${{ needs.package-bump.outputs.SHA }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ref: ${{ env.SHA }}
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'
        - name: Publish to Npm
          id: npm-steps
          run: npm publish --access public
          env:
             NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
