name: Bump version
on:
  push:
    branches:
      - main
jobs:
  bump:
    name: 'Bump version'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - uses: actions/checkout@v3
      - run: filter='to_entries | map("[\(.key)]=\(.value)") |
            reduce .[] as $item ("associativeArray=("; . + ($item|@sh) + " ") + ")"' && arrayAsString=$(cat ${{needs.bump}} | jq --raw-output "${filter}") && echo "$arrayAsString" && echo $associativeArray
      - uses: softprops/action-gh-release@v1

  publish-github:
      name: Publish github
      runs-on: ubuntu-latest
      needs: release
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            registry-url: 'https://npm.pkg.github.com'
            scope: '@mikey-pro'
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
      name: Publish npm
      runs-on: ubuntu-latest
      needs: release
      steps:
        - uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'
        - run: npm publish --access public
          env:
             NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
